### ISSUE TITLE
关于跨域的问题，希望解答

### ISSUE THREAD

**Issue by askwuxue** [pwx123/vue-vant-store#1]
你好，download了你的项目，想拿来研究研究，在跨域的问题上的问题我每太能明白。我也试着读了源码，还是不通，求解答。
![image](https://user-images.githubusercontent.com/32808762/46656753-5ccfc300-cbe1-11e8-87c5-ba625ab4ea4c.png)

**Comment by pwx123** [comment]
你好，这块我写的有些乱了，后端只允许127.0.0.1:8080跨域，不允许localhost:8080跨域，现在已经修改成通过反向代理跨域，可查看最新commit。

**Comment by askwuxue** [comment]
谢谢回复，有时间再看看


--------------原始邮件--------------
发件人："文祥 "<notifications@github.com>;
发送时间：2018年10月14日(星期天) 晚上9:03
收件人："pwx123/vue-vant-store" <vue-vant-store@noreply.github.com>;
抄送："askwuxue "<08153408@cumt.edu.cn>;"Author "<author@noreply.github.com>;
主题：Re: [pwx123/vue-vant-store] 关于跨域的问题，希望解答 (#1)
-----------------------------------

 
你好，这块我写的有些乱了，后端只允许127.0.0.1:8080跨域，不允许localhost:8080跨域，现在已经修改成通过反向代理跨域，可查看最新commit。
